import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1700, height: 1000 } })
await page.goto('http://localhost:5185/estimate/?editor=v2#/doc/7638c9c0-3642-4663-b76b-8ba08b5d7e72')
await page.locator('.est-edit-page').first().waitFor({ timeout: 10000 })
await page.waitForTimeout(800)
const tools = page.locator('.est-page-tools').first()
const visible = await tools.isVisible()
const opacity = await tools.evaluate(n => getComputedStyle(n).opacity)
const pageBox = await page.locator('.est-edit-page').first().boundingBox()
const toolsBox = await tools.boundingBox()
console.log('visible ohne Hover:', visible, '· opacity:', opacity)
console.log('rechts außerhalb der Seite:', toolsBox.x >= pageBox.x + pageBox.width)
await page.screenshot({ path: '/tmp/rail-verify.png', clip: { x: pageBox.x + pageBox.width - 240, y: pageBox.y - 10, width: 340, height: 260 } })
await browser.close()
